[package]
name = "rmpv"
version = "0.4.5"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Value variant for RMP"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmpv"
readme = "../README.md"
keywords = ["msgpack", "MessagePack", "serialization"]
categories = ["encoding"]
edition = "2018"

[features]
with-serde = ["serde", "serde_bytes"]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
serde_bytes = { path = "../../serde_bytes", version = "0.11.2", optional = true }
rmp = { version = "0.8.8", path = "../rmp" }
num-traits = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
serde = {  git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", features = ["derive"], optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
[dev-dependencies]
quickcheck = "0.9"
