[package]
name = "openssl-probe"
version = "0.1.3"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/openssl-probe"
homepage = "https://github.com/alexcrichton/openssl-probe"
description = """
Tool for helping to find SSL certificate locations on the system for OpenSSL
"""
readme = "README.md"
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["untrusted_fs"] }
