[package]
name = "run-tests-enclave"
version = "1.0.0"
edition = "2018"

[lib]
name = "run_tests_enclave"
crate-type = ["staticlib"]

[features]
default = []

# rename pkg to avoid updating src/lib.rs every time
[dependencies.wheel]
package = "rand"
path = "../.."
features = ["enclave_unit_test"]

[dependencies.wheel1]
package = "rand_distr"
path = "../../rand_distr"
features = ["enclave_unit_test"]

[dependencies.wheel2]
package = "rand_chacha"
path = "../../rand_chacha"
features = ["enclave_unit_test"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2" }