[package]
name = "tracing-log"
version = "0.1.1"
authors = ["Tokio Contributors <team@tokio.rs>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Provides compatibility between `tracing` and the `log` crate.
"""
categories = [
    "development-tools::debugging",
    "asynchronous",
]
keywords = ["logging", "tracing", "log"]
license = "MIT"
readme = "README.md"

[features]
default = ["log-tracer", "trace-logger", "std", "mesalock_sgx"]
std = ["log/std", "mesalock_sgx"]
log-tracer = []
trace-logger = []
mesalock_sgx = ["sgx_tstd", "std"]

[dependencies]
tracing-core = { path = "../tracing-core", version = "0.1.2"}
#log = { version = "0.4" }
#lazy_static = "1.3.0"
#env_logger = { version = "0.7", optional = true }

log = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
lazy_static = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
env_logger = { path = "../../env_logger", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
tracing = { path = "../tracing", version = "0.1"}

[badges]
maintenance = { status = "actively-maintained" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
