[package]
name = "tokio-mock-task"
# When releasing to crates.io:
# - Update html_root_url.
# - Create "v0.1.x" git tag.
version = "0.1.1"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/carllerche/tokio-mock-task"
homepage = "https://github.com/carllerche/tokio-mock-task"
documentation = "https://docs.rs/tokio-mock-task/0.1.0"
description = """
Mock a Tokio task
"""

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
#futures = "0.1.21"
futures = { path = "../futures-rs_01"}
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

