[package]
name = "tempfile"
version = "3.1.0"
authors = [
  "Steven Allen <steven@stebalien.com>",
  "The Rust Project Developers",
  "Ashley Mannix <ashleymannix@live.com.au>",
  "Jason White <jasonaw0@gmail.com>",
]
documentation = "https://docs.rs/tempfile"
edition = "2018"
exclude = ["/.travis.yml", "/appveyor.yml"]
homepage = "http://stebalien.com/projects/tempfile-rs"
keywords = ["tempfile", "tmpfile", "filesystem"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Stebalien/tempfile"
description = "A library for managing temporary files and directories."


[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "sgx_libc"]


[dependencies]
#cfg-if = "0.1"
#rand = "0.7"
#remove_dir_all = "0.5"
cfg-if = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
rand = { path = "../rand-0.7.3" }
remove_dir_all = { path = "../remove_dir_all"}

#[target.'cfg(unix)'.dependencies]
#libc = "0.2.27"
[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["untrusted_fs"] }
sgx_libc = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
    "fileapi",
    "handleapi",
    "winbase",
]

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1"
