[package]
name = "slog"
version = "2.6.0"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Structured, extensible, composable logging for Rust"
keywords = ["log", "logging", "structured", "hierarchical"]
categories = ["development-tools::debugging"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
documentation = "https://docs.rs/slog"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/slog"
readme = "README.md"
autoexamples = true

build = "build.rs"

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[features]
nested-values = ["erased-serde"]
dynamic-keys = []
std = ["mesalock_sgx"]
nothreads = []
default = ["std", "mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "std"]

max_level_off   = []
max_level_error = []
max_level_warn  = []
max_level_info  = []
max_level_debug = []
max_level_trace = []

release_max_level_off   = []
release_max_level_error = []
release_max_level_warn  = []
release_max_level_info  = []
release_max_level_debug = []
release_max_level_trace = []
enclave_unit_test = ["crates_unittest", "inventory"]
[dependencies]
erased-serde = { path = "../erased-serde", version = "0.3", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["untrusted_fs", "untrusted_time"] }
crates_unittest = { git = "https://github.com/Zha0Chan/crates-sgx-unittest.git", optional = true, default-features = false }
inventory = { version = "0.1.6", optional = true }
[[example]]
name = "singlethread"
required-features = ["nothreads"]

[package.metadata.docs.rs]
features = ["std", "nested-values", "dynamic-keys"]

[workspace]
members = [
  "crates/test_edition2018",
]
exclude = ["sgx-tests"]