[package]
name = "encoding-index-singlebyte"
version = "1.20141219.5"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Index tables for various single-byte character encodings"
homepage = "https://github.com/lifthrasiir/rust-encoding"
readme = "../../../README.md"
license = "CC0-1.0"
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
[lib]
name = "encoding_index_singlebyte"
path = "lib.rs"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
[dependencies.encoding_index_tests]
# TODO consider using dev-dependencies instead (Cargo issue #860)
version = "0.1.4"
path = "../tests"
