[package]

name = "traitobject"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-traitobject.git"
description = "Unsafe helpers for working with raw trait objects."
readme = "README.md"
license = "MIT/Apache-2.0"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }