[package]
name = "sharded-slab"
version = "0.0.9"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
documentation = "https://docs.rs/sharded-slab/0.0.9/sharded_slab"
homepage = "https://github.com/hawkw/sharded-slab"
repository = "https://github.com/hawkw/sharded-slab"
readme = "README.md"
license = "MIT"
keywords = ["slab", "allocator", "lock-free", "atomic"]
categories = ["memory-management", "data-structures", "concurrency"]
description = """
A lock-free concurrent slab.
"""

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[badges]
maintenance = { status = "experimental" }

[[bench]]
name = "bench"
harness = false

[dependencies]
lazy_static = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["thread"] }

#lazy_static = "1"

[dev-dependencies]
loom = { version = "0.3", features = ["checkpoint"] }
proptest = "0.9.4"
criterion = "0.3"
slab = "0.4.2"
