[package]
name = "tonic-health"
version = "0.2.0"
authors = ["James Nugent <james@jen20.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/hyperium/tonic"
homepage = "https://github.com/hyperium/tonic"
description = """
Health Checking module of `tonic` gRPC implementation.
"""
readme = "README.md"
categories = ["network-programming", "asynchronous"]
keywords = ["rpc", "grpc", "async", "healthcheck"]

[features]
default = ["transport", "mesalock_sgx"]
transport = ["tonic/transport"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
async-stream = { path = "../../async-stream/async-stream" }
tokio = { path = "../../tokio/tokio", version = "0.2", features = ["sync", "stream"] }
tonic = { version = "0.3", path = "../tonic", features = ["codegen", "prost"] }
bytes = { path = "../../bytes" }
prost = { path = "../../prost" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
# tokio = { version = "0.2", features = ["rt-core", "macros"]}

[build-dependencies]
tonic-build = { version = "0.3", path = "../tonic-build" }