[package]
name = "tokio-timer"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.2.x" git tag.
version = "0.2.13"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/tokio-timer/0.2.13/tokio_timer"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://github.com/tokio-rs/tokio"
description = """
Timer facilities for Tokio
"""

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
futures = { path = "../../futures-rs_01"}
tokio-executor = { path = "../tokio-executor"}
crossbeam-utils = { path = "../../crossbeam/crossbeam-utils"}

# Backs `DelayQueue`
slab = { path = "../../slab" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["untrusted_time"] }
#futures = "0.1.19"
#tokio-executor = "0.1.1"
#crossbeam-utils = "0.7.0"

# Backs `DelayQueue`
#slab = "0.4.1"

[dev-dependencies]
#rand = "0.7"
#tokio-mock-task = "0.1.0"
#tokio = "0.1.7"
