[package]

name = "tempdir"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.3.7"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/rust-lang/tempdir"
homepage = "https://github.com/rust-lang/tempdir"
documentation = "https://doc.rust-lang.org/tempdir"
description = """
A library for managing a temporary directory and deleting all contents when it's
dropped.
"""
categories = ["filesystem"]
keywords = ["fs", "file", "filesystem"]

[badges]
travis-ci = { repository = "rust-lang-nursery/tempdir" }
appveyor = { repository = "rust-lang-libs/tempdir" }

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
rand = { path = "../rand-0.7.3" }


[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["untrusted_fs"] }
remove_dir_all = { path = "../remove_dir_all" }

#rand = "0.4"
#remove_dir_all = "0.5"
