[package]

name = "unicase"
version = "1.0.0"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
description = "A case-insensitive wrapper around strings."
repository = "https://github.com/seanmonstar/unicase"
license = "MIT"
keywords = ["lowercase", "case", "case-insensitive"]
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }