[package]
name = "tokio-serde"
version = "0.6.1"
edition = "2018"
authors = [
    "Carl Lerche <me@carllerche.com>",
    "Artem Vorotnikov <artem@vorotnikov.me>",
    "Bastian Köcher <git@kchr.de>",
]
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["asynchronous", "encoding"]
keywords = ["async", "serde", "serialization"]
repository = "https://github.com/carllerche/tokio-serde"
homepage = "https://github.com/carllerche/tokio-serde"
documentation = "https://docs.rs/tokio-serde"
description = """
Send and receive Serde encodable types over the network using Tokio.

This library is used as a building block for serialization format specific
libraries.
"""

[dependencies]
bytes = { path = "../bytes"}
derivative = { version = "2", optional = true }
futures = { path = "../futures-rs/futures" }
pin-project = "0.4"
serde = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", features = ["derive"], optional = true }
bincode-crate = { package = "bincode", path = "../bincode", version = "1", optional = true }
serde_json = { path = "../json", version = "1", optional = true }
rmp-serde = { path = "../msgpack-rust/rmp-serde", version = "0.14", optional = true }
serde_cbor = { path = "../cbor", version = "0.11", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.3", features = ["full"] }
static_assertions = "1.1.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
bincode = ["derivative", "serde", "bincode-crate"]
json = ["derivative", "serde", "serde_json"]
messagepack = ["derivative", "serde", "rmp-serde"]
cbor = ["derivative", "serde", "serde_cbor"]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
[[example]]
name = "client"
required-features = ["bincode", "cbor", "json", "messagepack"]

[[example]]
name = "server"
required-features = ["bincode", "cbor", "json", "messagepack"]
