[package]
name = "tower-test"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.3.0"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-test/0.3.0-alpha.2"
description = """
Utilities for writing client and server `Service` tests.
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
futures-util = { path = "../../futures-rs/futures-util", version = "0.3" }
tokio = { path = "../../tokio/tokio", version = "0.2", features = ["sync"]}
tower-layer = { path = "../tower-layer", version = "0.3" }
tokio-test = { path = "../../tokio/tokio-test" }
tower-service = { path = "../tower-service", version = "0.3" }
pin-project = "0.4"
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

# [dev-dependencies]
# tokio = { version = "0.2", features = ["macros"] }