[workspace]

members = [
  "tokio",
<<<<<<< HEAD
  "tokio-macros",
  "tokio-test",
  "tokio-util",

  # Internal
  "benches",
  "examples",
  "tests-build",
  "tests-integration",
=======
  "tokio-buf",
  "tokio-codec",
  "tokio-current-thread",
  "tokio-executor",
  "tokio-fs",
  "tokio-futures",
  "tokio-io",
  "tokio-process",
  "tokio-reactor",
  "tokio-signal",
  "tokio-sync",
  "tokio-test",
  "tokio-threadpool",
  "tokio-timer",
  "tokio-tcp",
  "tokio-tls",
  "tokio-udp",
  "tokio-uds",
>>>>>>> e096857bc25c075b1b62e88811fc6fc0c42905b5
]
