[package]
name = "form_urlencoded"
version = "1.0.0"
authors = ["The rust-url developers"]
description = "Parser and serializer for the application/x-www-form-urlencoded syntax, as used by HTML forms."
repository = "https://github.com/servo/rust-url"
license = "MIT/Apache-2.0"
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[lib]
test = false

[dependencies]
matches = { path = "../../matches" }
percent-encoding = { version = "2.1.0", path = "../percent_encoding" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }