[package]
name = "run-tests-enclave"
version = "1.0.0"
edition = "2018"

[lib]
name = "run_tests_enclave"
crate-type = ["staticlib"]

[workspace] 

[features]
default = ["mesalock_sgx", "crates_unittest", "inventory"]
mesalock_sgx = ["sgx_tstd"]


[dependencies]
inventory = { version = "0.1.6", optional = true }
crates_unittest = { git = "https://github.com/Zha0Chan/crates-sgx-unittest.git", optional = true, default-features = false }
indexmap = { path = "../.." }
itertools = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
rand = { path = "../../../rand-0.7.3" }
quickcheck = { path = "../../../quickcheck" }
fnv = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
# lazy_static = {}
# serde_test = "1.0.99"
[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["backtrace", "thread", "untrusted_fs", "untrusted_time", "net"] }
