name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo check
      - run: cargo check --manifest-path tests/crate/Cargo.toml
      - run: cargo check --manifest-path tests/crate/Cargo.toml --no-default-features --features alloc
      - run: cargo test

  msrv:
    name: Rust 1.31.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@1.31.0
      - run: cargo check
      - run: cargo check --manifest-path tests/crate/Cargo.toml
