[package]

name = "tower-util"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.3.x" git tag.
version = "0.3.1"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-util/0.3.1"
description = """
Utilities for working with `Service`.
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"

[features]
default = ["call-all", "mesalock_sgx"]
call-all = ["futures-util"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
tower-service ={ version = "0.3", path = "../tower-service" }
pin-project = "0.4"
futures-core = { path = "../../futures-rs/futures-core", version = "0.3" }

# Optional

futures-util = { path = "../../futures-rs/futures-util", version = "0.3", optional = true, features = ["alloc"] }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
tokio-test = "0.2"
tokio = { version = "0.2", features = ["stream", "sync", "macros"] }
tower-test = { version = "0.3", path = "../tower-test" }
