[package]
name = "tokio-buf"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.1"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-buf/0.1.1/tokio_buf"
description = """
Asynchronous stream of byte buffers
"""
categories = ["asynchronous"]

[dependencies]
bytes = { path = "../../bytes-0.4.x" }
either = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", optional = true }
futures = { path = "../../futures-rs_01" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

#bytes = "0.4.10"
#either = { version =  "1.5", optional = true }
#futures = "0.1.23"


[features]
default = ["util", "mesalock_sgx"]
#util = ["bytes/either", "either"]
util = ["bytes/either", "either"]
mesalock_sgx = ["sgx_tstd"]

[dev-dependencies]
#tokio-mock-task = "0.1.1"
