[package]
name = "tower-balance"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.3.0"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-balance/0.3.0"
description = """
Balance load across a set of uniform services.
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"

[features]
log = ["tracing/log"]
default = ["log", "mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
futures-util = { path = "../../futures-rs/futures-util", version = "0.3" } 
futures-core = { path = "../../futures-rs/futures-core", version = "0.3" }
pin-project = "0.4"
indexmap = { path = "../../indexmap" }
tracing = { path = "../../tracing/tracing" }
rand = { path = "../../rand-0.7.3", version = "0.7", features = ["small_rng"] } 
tokio = { path = "../../tokio/tokio", version = "0.2", features = ["sync", "time"] }
tower-discover = { version = "0.3", path = "../tower-discover" }
tower-layer = { version = "0.3", path = "../tower-layer" }
tower-load = { version = "0.3", path = "../tower-load" }
tower-service = { version = "0.3", path = "../tower-service" }
tower-ready-cache = { version = "0.3", path = "../tower-ready-cache" }
tower-make = { version = "0.3", path = "../tower-make" }
slab = { path = "../../slab" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
# tracing-subscriber = "0.1.1"
# hdrhistogram = "6.0"
# quickcheck = { version = "0.6", default-features = false }
# tokio = { version = "0.2", features = ["macros"] } 
# tokio-test = "0.2"
# tower-buffer = { version = "0.3", path = "../tower-buffer" }
# tower-limit = { version = "0.3", path = "../tower-limit" }
# tower-test = { version = "0.3", path = "../tower-test" }
# tower = { version = "0.3", path = "../tower" }
