[package]
name = "tracing-tower"
version = "0.1.0"
authors = ["Eliza Weisman <eliza@buoyant.io>"]
edition = "2018"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Compatibility with the `tower` ecosystem.
"""
categories = [
    "development-tools::debugging",
    "development-tools::profiling",
    "asynchronous",
]
keywords = ["logging", "tracing"]
license = "MIT"

[features]
default = ["mesalock_sgx", "tower-layer", "tower-make", "http"]
tower-make = [
    "tower_make",
    "pin-project",
]
mesalock_sgx = ["sgx_tstd"]

[dependencies.tower_make]
package = "tower"
features = ["make"]
path = "../../tower/tower"
version = "0.3"
optional = true

[dependencies]
tracing = { path = "../tracing", version = "0.1"}
tracing-futures = { version = "0.2.1", path = "../tracing-futures", features = ["std-future"] }
#futures = "0.3"
#tower-service = "0.3"
#tower-layer = { version = "0.3", optional = true }
#tower_make = { package = "tower-make", version = "0.3", optional = true }

futures = { path = "../../futures-rs/futures" }
tower-service = { path = "../../tower-0.3.x/tower-service" }
tower-layer = { path = "../../tower-0.3.x/tower-layer", optional = true }
#tower_make = { package = "tower-make", path = "../../tower-make-0.3.0", version = "0.3", optional = true }


pin-project = { version = "0.4", optional = true }
#http = { version = "0.2", optional = true }
http = { path = "../../http", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
