[package]
name = "tokio-tcp"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.4"
authors = ["Carl Lerche <me@carllerche.com>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-tcp/0.1.4/tokio_tcp"
description = """
TCP bindings for tokio.
"""
categories = ["asynchronous"]

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
tokio-io = { path = "../tokio-io"}
tokio-reactor = { path = "../tokio-reactor"}
bytes = { path = "../../bytes-0.4.x" }
mio = { path = "../../mio-0.6.x" }
iovec = { path = "../../iovec" }
futures = { path = "../../futures-rs_01"}
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["net"] }
#tokio-io = "0.1.6"
#tokio-reactor = "0.1.1"
#bytes = "0.4"
#mio = "0.6.14"
#iovec = "0.1"
#futures = "0.1.19"

[dev-dependencies]
#env_logger = { version = "0.6", default-features = false }
#net2 = "0.2"
#tokio = "0.1.13"
