[package]
name = "sct"
version = "0.6.0"
edition = "2018"
authors = ["Joseph Birr-Pixton <jpixton@gmail.com>"]
description = "Certificate transparency SCT verification library"
license = "Apache-2.0/ISC/MIT"
readme = "README.md"
homepage = "https://github.com/ctz/sct.rs"
repository = "https://github.com/ctz/sct.rs"
categories = ["network-programming", "cryptography"]

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
ring = { path = "../ring" }
untrusted = "0.7.0"
