[package]
name = "tokio-util"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
# - Update CHANGELOG.md.
# - Create "v0.2.x" git tag.
version = "0.3.1"
edition = "2018"
authors = ["Tokio Contributors <team@tokio.rs>"]
license = "MIT"
repository = "https://github.com/tokio-rs/tokio"
homepage = "https://tokio.rs"
documentation = "https://docs.rs/tokio-util/0.3.1/tokio_util"
description = """
Additional utilities for working with Tokio.
"""
categories = ["asynchronous"]

[features]
# No features on by default
default = ["mesalock_sgx"]

# Shorthand for enabling everything
full = ["codec", "udp", "compat", "mesalock_sgx"]

compat = ["futures-io",]
codec = ["tokio/stream"]
udp = ["tokio/udp"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
tokio = { version = "0.2.5", path = "../tokio" }

#bytes = "0.5.0"
#futures-core = "0.3.0"
#futures-sink = "0.3.0"
#log = "0.4"
pin-project-lite = "0.1.4"

bytes = { path = "../../bytes" }
log = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
futures-core = { path = "../../futures-rs/futures-core" }
futures-sink = { path = "../../futures-rs/futures-sink" }
futures-io = { path = "../../futures-rs/futures-io" , optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["net"] }
[dev-dependencies]
tokio = { version = "0.2.0", path = "../tokio", features = ["full"] }
tokio-test = { version = "0.2.0", path = "../tokio-test" }

futures = "0.3.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
