[package]
name = "take_mut"
version = "0.2.2"
authors = ["Sgeo <sgeoster@gmail.com>"]
license = "MIT"
homepage = "https://github.com/Sgeo/take_mut"
repository = "https://github.com/Sgeo/take_mut"
description = "Take a T from a &mut T temporarily"
categories = ["rust-patterns"]

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "sgx_trts"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
sgx_trts = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
