[package]
name    = "quoted-string"
version = "0.2.2"

authors = ["Philipp Korber <p.korber@1aim.com>"]
license = "MIT/Apache-2.0"

description   = "Utilities to handle quoted strings (in mail, MIME types, ..)"
readme        = "README.md"
documentation = "https://docs.rs/quoted-string"
repository    = "https://github.com/1aim/quoted-string"
keywords      = ["mail", "quoted", "mime", "string", "rfc5322"]
categories    = ["encoding"]

[badges]
travis-ci = { repository = "1aim/quoted-string", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
#quick-error = "1.2.1"
quick-error = { path = "../quick-error-1.2.1" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
