[package]
name = "tracing-error"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag
version = "0.1.2"
authors = [
    "Eliza Weisman <eliza@buoyant.io>",
    "Jane Lusby <jlusby@yaah.dev>",
    "Tokio Contributors <team@tokio.rs>"
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tokio-rs/tracing"
homepage = "https://tokio.rs"
description = """
Utilities for enriching errors with `tracing`.
"""
categories = [
    "development-tools::debugging",
    "rust-patterns"
]
keywords = [
    "tracing",
    "error-handling",
    "exception-reporting",
    "backtrace"
]
edition = "2018"


[features]
default = ["traced-error", "mesalock_sgx"]
traced-error = []
mesalock_sgx = ["sgx_tstd"]
enclave_unit_test = ["crates_unittest", "inventory"]

[dependencies]
tracing-subscriber = { path = "../tracing-subscriber", version = "0.2.7", default-features = false, features = ["registry", "fmt"] }
tracing = { path = "../tracing", version = "0.1.12"}
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
crates_unittest = { git = "https://github.com/Zha0Chan/crates-sgx-unittest.git", optional = true, default-features = false }
inventory = { version = "0.1.6", optional = true }
[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
