[package]
name = "parking_lot_core"
version = "0.8.0"
authors = ["Amanieu d'Antras <amanieu@gmail.com>"]
description = "An advanced API for creating custom synchronization primitives."
license = "Apache-2.0/MIT"
repository = "https://github.com/Amanieu/parking_lot"
keywords = ["mutex", "condvar", "rwlock", "once", "thread"]
categories = ["concurrency"]
edition = "2018"


[dependencies]
cfg-if = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2" }
smallvec = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", features = ["write", "union", "specialization", "may_dangle", "serde"] }
petgraph = { path = "../../petgraph", version = "0.5", optional = true }
thread-id = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", optional = true }
#backtrace = { git = "https://github.com/mesalock-linux/libbacktrace-sgx", optional = true }
instant = { path = "../../instant" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["thread", "backtrace"] }
sgx_libc = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
sgx_backtrace = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
#cfg-if = "0.1.10"
#smallvec = "1.4.0"
#petgraph = { version = "0.5.1", optional = true }
#thread-id = { version = "3.3.0", optional = true }
#backtrace = { version = "0.3.49", optional = true }
#instant = "0.1.4"

#[target.'cfg(unix)'.dependencies]
#libc = "0.2.71"

[target.'cfg(target_os = "redox")'.dependencies]
redox_syscall = "0.1.56"

[target.'cfg(target_os = "cloudabi")'.dependencies]
cloudabi = "0.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winnt", "ntstatus", "minwindef",
    "winerror", "winbase", "errhandlingapi", "handleapi"] }





[features]
default = ["mesalock_sgx"]
nightly = []
deadlock_detection = ["petgraph", "thread-id", "sgx_backtrace"]
mesalock_sgx = ["sgx_tstd", "sgx_libc"]
