[package]
name = "prost-types"
version = "0.6.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-types"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2018"

[lib]
doctest = false

[features]
default = ["std", "mesalock_sgx"]
std = ["prost/std", "sgx_tstd"]
mesalock_sgx = ["sgx_tstd", "std"]

[dependencies]
bytes = { path = "../../bytes", version = "0.5" }
prost = { version = "0.6.1", path = "..", features = ["prost-derive"] }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
[dev-dependencies]
proptest = "0.9"
