[package]
name = "tower-ready-cache"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.3.1"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-ready-cache/0.3.1"
description = """
Caches a set of services
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"


[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]


[dependencies]
futures-core = { path = "../../futures-rs/futures-core", version = "0.3" }
futures-util = { path = "../../futures-rs/futures-util", version = "0.3", features = ["alloc"] }
indexmap = { path = "../../indexmap" }
log = { path = "../../log" }
tokio = { path = "../../tokio/tokio", version = "0.2", features = ["sync"] } 
tower-service = { version = "0.3", path = "../tower-service" }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
tower-test = { version = "0.3", path = "../tower-test" }
tokio-test = "0.2"

