[package]
name = "tokio-rustls"
version = "0.14.0"
authors = ["quininer kel <quininer@live.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/tokio-rs/tls"
homepage = "https://github.com/tokio-rs/tls"
documentation = "https://docs.rs/tokio-rustls"
readme = "README.md"
description = "Asynchronous TLS/SSL streams for Tokio using Rustls."
categories = ["asynchronous", "cryptography", "network-programming"]
edition = "2018"

[dependencies]
tokio = { path = "../../tokio/tokio"}
futures-core = { path = "../../futures-rs/futures-core" }
rustls = { path = "../../rustls/rustls" }
webpki = { path = "../../webpki" }
bytes = { path = "../../bytes", version = "0.5", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
# tokio = "0.2.0"
# futures-core = "0.3.1"
# rustls = "0.18"
# webpki = "0.21"

#bytes = { version = "0.5", optional = true }

[features]
default = ["mesalock_sgx"]
early-data = []
dangerous_configuration = ["rustls/dangerous_configuration"]
unstable = ["bytes"]
mesalock_sgx = ["sgx_tstd"]

[dev-dependencies]
# tokio = { version = "0.2.0", features = ["macros", "net", "io-util", "rt-core", "time"] }
# futures-util = "0.3.1"
# lazy_static = "1"
# webpki-roots = "0.20"
