[package]
name = "standback"
version = "0.2.9"
authors = ["Jacob Pratt <the.z.cuber@gmail.com>", "The Rust Project Developers"]
edition = "2018"
repository = "https://github.com/jhpratt/standback"
keywords = ["std", "back-compatible", "polyfill"]
categories = ["no-std"]
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "New standard library, old compiler."
build = "build.rs"



[features]
default = ["std"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[build-dependencies]
version_check = "0.9.2"