[package]
name = "mio-uds"
version = "0.6.8"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/deprecrated/mio-uds"
homepage = "https://github.com/deprecrated/mio-uds"
documentation = "https://docs.rs/mio-uds"
description = """
Unix domain socket bindings for mio
"""
categories = ["asynchronous"]
include = [
  "Cargo.toml",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "src/**/*.rs"
]
[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "sgx_libc"]

[target."cfg(unix)".dependencies]
iovec = { path = "../iovec" }
mio = { path = "../mio-0.6.x" }
#iovec = "0.1"
#libc = "0.2.69"
#mio = "0.6.5"

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true, features = ["net"] }
sgx_libc = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[dev-dependencies]
#tempdir = "0.3"

