[package]
name = "futures-sink"
edition = "2018"
version = "0.3.5"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/futures-rs"
homepage = "https://rust-lang.github.io/futures-rs"
documentation = "https://docs.rs/futures-sink/0.3.5"
description = """
The asynchronous `Sink` trait for the futures-rs library.
"""

[features]
default = ["std", "mesalock_sgx"]
std = ["mesalock_sgx", "alloc"]
alloc = []
mesalock_sgx = ["sgx_tstd", "std"]

[dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[package.metadata.docs.rs]
all-features = true
