[package]

name = "url"
# When updating version, also modify html_root_url in the lib.rs
version = "2.1.1"
authors = ["The rust-url developers"]

description = "URL library for Rust, based on the WHATWG URL Standard"
documentation = "https://docs.rs/url"
repository = "https://github.com/servo/rust-url"
readme = "README.md"
keywords = ["url", "parser"]
categories = ["parser-implementations", "web-programming", "encoding"]
license = "MIT/Apache-2.0"

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "servo/rust-url" }
appveyor = { repository = "Manishearth/rust-url" }

[workspace]
members = [".", "form_urlencoded", "idna", "percent_encoding", "data-url"]

[[test]]
name = "unit"

[[test]]
name = "data"
harness = false

[lib]
test = false

[dev-dependencies]
# rustc-test = "0.3"
# serde_json = "1.0"

# bencher = "0.1"

[dependencies]
form_urlencoded = { version = "1.0.0", path = "./form_urlencoded" }
idna = { version = "0.2.0", path = "./idna" }
matches = { path = "../matches" }
percent-encoding = { version = "2.1.0", path = "./percent_encoding" }
serde = { git = "https://github.com/universal-secure-computing-community/crates-sgx.git", tag = "v0.3.1+sgx1.1.2", features = ["derive"], optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
[[bench]]
name = "parse_url"
harness = false
