[package]
name = "termcolor"
version = "1.1.0"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
A simple cross platform library for writing colored text to a terminal.
"""
documentation = "https://docs.rs/termcolor"
homepage = "https://github.com/BurntSushi/termcolor"
repository = "https://github.com/BurntSushi/termcolor"
readme = "README.md"
keywords = ["windows", "win", "color", "ansi", "console"]
license = "Unlicense OR MIT"
exclude = ["/.travis.yml", "/appveyor.yml", "/ci/**"]
edition = "2018"

[lib]
name = "termcolor"
bench = false

[features]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }

[target.'cfg(windows)'.dependencies]
winapi-util = "0.1.3"

[dev-dependencies]
doc-comment = "0.3"
