[package]
name = "rle-decode-fast"
version = "1.0.2-alpha.0"
authors = ["Moritz Wanzenböck <moritz@wanzenbug.xyz>"]
edition = "2015"
license = "MIT OR Apache-2.0"
description = """
THE fastest way to implement any kind of decoding for Run Length Encoded data in Rust.

Writing a fast decoder that is also safe can be quite challenging, so this crate is here to save you the
hassle of maintaining and testing your own implementation.
"""
repository = "https://github.com/WanzenBug/rle-decode-helper"
readme = "README.md"

[[bench]]
name = "bench"
harness = false
required-features = ["bench"]

[features]
bench = ["criterion"]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]
[dependencies]
criterion = { version = "0.2", optional = true }
sgx_tstd = { git = "https://github.com/apache/incubator-teaclave-sgx-sdk.git", tag = "v1.1.2", optional = true }
